((nil . (
         (indent-tabs-mode . t)
         (c-basic-offset . 8)
         (tab-width . 8)
         (js-indent-level . 8)))
 (js-mode . (
             (indent-tabs-mode . t)
             (c-basic-offset . 8)
             (tab-width . 8)
             (js-indent-level . 8)))
 (javascript-mode . (
                     (indent-tabs-mode . t)
                     (c-basic-offset . 8)
                     (tab-width . 8)
                     (js-indent-level . 8)))
 (js2-mode . (
              (indent-tabs-mode . t)
              (c-basic-offset . 8)
              (tab-width . 8)
              (js-indent-level . 8))))
